server:
  port: 8281
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/takeout
    username: root
    password: 123456
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/chj/mapper/xml/*.xml
rocketmq:
  name-server: 192.168.59.128:9876
  producer:
    group: order